In [1]:
import pandas as pd
import numpy as np

C:\Users\Atharva\AppData\Local\Temp\ipykernel_16736\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [5]:
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df=pd.read_csv("../10/Iris.csv",names=column_names)

In [6]:
df

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [7]:
df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
subset1=df[df['class']=='Iris-setosa']
subset2=df[df['class']=='Iris-versicolor']
subset3=df[df['class']=='Iris-virginica']

In [10]:
merge=pd.concat([subset1,subset2])
merge

    sepal_length  sepal_width  petal_length  petal_width            class
0            5.1          3.5           1.4          0.2      Iris-setosa
1            4.9          3.0           1.4          0.2      Iris-setosa
2            4.7          3.2           1.3          0.2      Iris-setosa
3            4.6          3.1           1.5          0.2      Iris-setosa
4            5.0          3.6           1.4          0.2      Iris-setosa
..           ...          ...           ...          ...              ...
95           5.7          3.0           4.2          1.2  Iris-versicolor
96           5.7          2.9           4.2          1.3  Iris-versicolor
97           6.2          2.9           4.3          1.3  Iris-versicolor
98           5.1          2.5           3.0          1.1  Iris-versicolor
99           5.7          2.8           4.1          1.3  Iris-versicolor

[100 rows x 5 columns]

In [13]:
sort=df.sort_values('petal_length')
sort

     sepal_length  sepal_width  petal_length  petal_width           class
22            4.6          3.6           1.0          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
35            5.0          3.2           1.2          0.2     Iris-setosa
36            5.5          3.5           1.3          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
131           7.9          3.8           6.4          2.0  Iris-virginica
105           7.6          3.0           6.6          2.1  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica

[150 rows x 5 columns]

In [15]:
transpose=df.transpose()
transpose

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
sepal_length,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
sepal_width,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
petal_length,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
petal_width,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
class,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [19]:
melt=pd.melt(df,id_vars=['sepal_length','petal_length','class'], var_name='attribute',value_name='value')
melt

     sepal_length  petal_length           class    attribute  value
0             5.1           1.4     Iris-setosa  sepal_width    3.5
1             4.9           1.4     Iris-setosa  sepal_width    3.0
2             4.7           1.3     Iris-setosa  sepal_width    3.2
3             4.6           1.5     Iris-setosa  sepal_width    3.1
4             5.0           1.4     Iris-setosa  sepal_width    3.6
..            ...           ...             ...          ...    ...
295           6.7           5.2  Iris-virginica  petal_width    2.3
296           6.3           5.0  Iris-virginica  petal_width    1.9
297           6.5           5.2  Iris-virginica  petal_width    2.0
298           6.2           5.4  Iris-virginica  petal_width    2.3
299           5.9           5.1  Iris-virginica  petal_width    1.8

[300 rows x 5 columns]

In [24]:
cast=df.pivot_table(df,index='class')
cast

                 petal_length  petal_width  sepal_length  sepal_width
class
Iris-setosa             1.464        0.244         5.006        3.418
Iris-versicolor         4.260        1.326         5.936        2.770
Iris-virginica          5.552        2.026         6.588        2.974